title: Bridge Dataset
description: A large and diverse robotic manipulation dataset for research in learning-based robotics.
show_downloads: true
theme: jekyll-theme-cayman
github:
  is_project_page: false